### ISSUE TITLE
AB Container

### ISSUE THREAD

**Issue by bradpotter** [studiopress/atomic-blocks#109]
Please consider adding the option to adjust padding and margin in "pixels" or percentage.

**Comment by mikemcalister** [comment]
Hi Brad, 

Thanks for the heads up! We just added this to our upcoming Advanced Column block, which is launching today. We'll look at adding this to the other blocks as well.

**Comment by bradpotter** [comment]
Thank you Mike. Look forward to the upcoming Advanced Column block and pixel based padding/margin in the AB Container.

**Comment by mikemcalister** [comment]
Going to close this issue as the request is in our backlog for the plugin.
