### ISSUE TITLE
AMP compatibility

### ISSUE THREAD

**Issue by mindctrl** [studiopress/atomic-blocks#111]
We want to make Atomic Blocks compatible with AMP as much as is possible and reasonable. This issue will track all the changes required for that. I'll update the list below if other issues are discovered.

**Issues**
- [x] Newsletter block doesn't render. It uses jQuery and AJAX. This will need to be updated to support `<amp-form>` with `<action-xhr>`. The form will be updated to use AMP redirect after submission.
- [x] Notice block uses JS for dismissing the notice. This will need to be refactored later to work out a different method of hiding/showing notices since it currently defaults to hiding them and only shows them if the visitor has not dismissed it.
- [x] Pricing table block triggers an error due to `<span placeholder="$">`. Specifically the `placeholder` is the issue.
- [x] Sharing block uses JS and outputs it on every page on the `wp_footer` hook. Needs to be refactored to only output on regular non-AMP requests. Links on AMP requests will be normal links with no JS trigger.

**Comment by fvdzbd** [comment]
I can't create Tables in AMP Pages, give a solution

**Comment by mindctrl** [comment]
@fvdzbd Atomic Blocks doesn't have a table block. Unless you're seeing a conflict with the WP core table block and Atomic Blocks specifically, we won't be able to help with that.
