### ISSUE TITLE
Notices: Dismiss icon shows after changing type to Always Show

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/atomic-blocks#118]
Steps to replicate:
1. Add a notice set to "Dismissible" and save
2. Change the notice type to "Always Show" and save
3. View the page

The icon will still show as if it is dismissible.

**Comment by nickcernis** [comment]
Also occurs if skipping the save step.

![ab-notice-dismiss](https://user-images.githubusercontent.com/647669/57525344-bf7d6e80-732a-11e9-8238-ab1b491a8748.gif)

The block container also gains classes of 'Always Show' (back and front end) when switching to “Always Show” from “Dismissible”:
 
<img width="498" alt="Screenshot 2019-05-10 at 13 52 28" src="https://user-images.githubusercontent.com/647669/57525412-f05da380-732a-11e9-93d1-a40269694dd9.png">
