### ISSUE TITLE
Feature: Default settings for Post/Page Grid block

### ISSUE THREAD

**Issue by mindctrl** [studiopress/atomic-blocks#128]
Logging here to track interest to see if demand warrants development.

User requested a way set values for the block so that each time it's added to a page those settings are used by default.

**Requests**
https://wordpress.org/support/topic/set-my-own-defaults-for-post-and-page-grid/

**Comment by mikemcalister** [comment]
I think a default setting system for all blocks is valuable, and something that we've talked about. Going to close this one for now and sweep it under that request.
