### ISSUE TITLE
Accordion block : Open from hash link

### ISSUE THREAD

**Issue by audiovisuel-uqam** [studiopress/atomic-blocks#138]
A typical feature from other accordions is to be able to link to an open accordion with a hash.
For example `https://example.ltd/contact#sales` would open the sales accordion.

**Comment by mikemcalister** [comment]
Hi @audiovisuel-uqam, if we rework the accordion to a JS based approach, we can implement this. Right now, the accordion uses a simpler [details/summary](https://css-tricks.com/quick-reminder-that-details-summary-is-the-easiest-way-ever-to-make-an-accordion/) method for doing accordions.
