### ISSUE TITLE
Remove font-size option or override .ab-font-size-[n] css

### ISSUE THREAD

**Issue by campaignupgrade** [studiopress/atomic-blocks#144]
My theme defines font sizes for various conditions — element placement, viewport size, etc. 

`.ab-font-size-18` etc is interfering with this. 

Is there any way to disable font size selection inside the Gutenberg block editor, or failing that an easy way to disable all AB font-size styles? 

Writing CSS to override each instance of .ab-font-size-[n] > [element] is possible but seems like overkill.

**Comment by mikemcalister** [comment]
Let us know if you're still seeing this on a specific block. We've moved to outputting font sizes only when they're set.
