### ISSUE TITLE
Landscape/Square image size issue in Post Grid

### ISSUE THREAD

**Issue by mikemcalister** [studiopress/atomic-blocks#158]
Users of the post grid block are seeing some issues with the landscape/square image sizes. Without digging in, it looks like there's a few things going on here. Firstly, it seems like this was introduced after we added the image size options. Secondly, I don't think we need the Featured Image Style drop down, since the image sizes are now in the Image Size drop down.

Detailed conversation about the issue can be found here: https://genesiswp.slack.com/archives/CAKLFDJ5A/p1561254453043300

**Comment by mindctrl** [comment]
> I don't think we need the Featured Image Style drop down, since the image sizes are now in the Image Size drop down.

Sounds right to me.
