### ISSUE TITLE
Text Spacing issues in Author and CTA Blocks

### ISSUE THREAD

**Issue by pawangif** [studiopress/atomic-blocks#166]
Hello,
I just started using Atomic Blocks and I'm in love with this concept as it can save me from installing tonnes of other plugins. But I'm facing an issue with the spacing between the text and couldn't find any toggle to set it up.
The theme I'm using is Divi. I've attached the screenshot of the issue.
![github atomic blocks feedback](https://user-images.githubusercontent.com/52773911/61026752-dd6e5a80-a3d1-11e9-8cca-702bab0e22d7.png)

**Comment by mindctrl** [comment]
@pawangif My guess is your theme is causing the issue by being heavy handed with styles.

We only use GitHub for development tracking, but feel free to open a support thread on the support forums here and we'll see if we can help: https://wordpress.org/support/plugin/atomic-blocks/
