### ISSUE TITLE
Fix deprecated uses of withColors and withFontSizes

### ISSUE THREAD

**Issue by mindctrl** [studiopress/atomic-blocks#200]
Some of our blocks are using `withColors` and `withFontSizes` from `wp.editor`. A recent version of WordPress moved these to `wp.blockEditor`. This causes the following deprecation notices to be triggered:

```
wp.editor.withFontSizes is deprecated and will be removed. Please use wp.blockEditor.withFontSizes instead.

wp.editor.withColors is deprecated and will be removed. Please use wp.blockEditor.withColors instead.
```

We need to change these in a backwards compatible way, so that users on versions of WP that still use `wp.editor` won't break. Maybe we bump our min WP version requirement since a there are numerous examples like this happening in core.

**Comment by mindctrl** [comment]
Other notices

```
wp.editor.BlockControls is deprecated and will be removed. Please use wp.blockEditor.BlockControls instead.

wp.editor.BlockAlignmentToolbar is deprecated and will be removed. Please use wp.blockEditor.BlockAlignmentToolbar instead.

wp.editor.InspectorControls is deprecated and will be removed. Please use wp.blockEditor.InspectorControls instead.

wp.editor.InnerBlocks is deprecated and will be removed. Please use wp.blockEditor.InnerBlocks instead.

wp.editor.PanelColorSettings is deprecated and will be removed. Please use wp.blockEditor.PanelColorSettings instead.
```

**Comment by mikemcalister** [comment]
`wp.editor` is moving to `wp.blockEditor`. We'll need to update these soon and bump the minimum support to 5.2. More [here](https://make.wordpress.org/core/2019/04/09/the-block-editor-javascript-module-in-5-2/).
