### ISSUE TITLE
Cannot read property 'columnVerticalAlignment' of undefined

### ISSUE THREAD

**Issue by nickcernis** [studiopress/atomic-blocks#202]
**Describe the bug**
I see “Cannot read property 'columnVerticalAlignment' of undefined” in Chrome when accessing the editor under WordPress 5.0 with Atomic Blocks 2.0.1 (or latest develop branch) active.

This crashes the block editor.

<img width="1213" alt="Screen Shot 2019-08-13 at 20 18 43" src="https://user-images.githubusercontent.com/647669/62966578-937cf800-be07-11e9-888a-9f50fb50497a.png">

The error is not visible with WordPress 5.2.2 active.

No other plugins are active.

When running `npm start` Chrome points to the error here in `src/blocks/block-column-inner/index.js`:

```js
if ( props.attributes.columnVerticalAlignment && 'atomic-blocks/ab-column' === blockName ) {
```

Changing it to this solves the issue for me (`props.block.attributes` instead of `props.attributes`):

```js
if ( 'atomic-blocks/ab-column' === blockName && props.block.attributes.columnVerticalAlignment ) {
```

This works because `props.attributes` doesn't seem to be available under WP 5.0 in that context, but `props.block.attributes` is available under both 5.0 and 5.2.

Changing the order of conditions to test for the `ab-column` block first isn't required for the fix but may be faster since the other condition only needs to be checked if it's an ab-column block.

Pull request at https://github.com/studiopress/atomic-blocks/pull/203.

**To Reproduce**
Under WP 5.0:
1. Visit `http://example.com/wp-admin/post-new.php?post_type=page` with Atomic Blocks active.
2. Click in the main editor section to add a block.

You'll see the error mentioned above.

**Expected behavior**
Atomic Blocks gives a [minimum version](https://wordpress.org/plugins/atomic-blocks/) of WP 4.7, so expected it to work under 5.0.

**Version**
- 2.0.1
- Latest develop branch as of 916f875.

**Device and browser information**
- Chrome

**Comment by mindctrl** [comment]
Fixed in #208.
