### ISSUE TITLE
AB Posts Section Title class not output on front end

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/atomic-blocks#229]
**Describe the bug**

`.ab-post-grid-section-title` is available in the editor for styling, but is absent on the front end.

**To Reproduce**

1. Add an AB Post Grid block to a page
2. Under Page and Post Grid Content, toggle the Section Title on and enter a section title.
3. Inspect the source in the editor. You should see `ab-post-grid-section-title` as the class used for the heading.
4. Inspect the source on the front end. You will see there is no class for the section title.

**Expected behavior**
The `ab-post-grid-section-title` class will be available on the front end to use for styling.

**Screenshots**

**Version**
- develop/master

**Comment by mindctrl** [comment]
Fixed in https://github.com/studiopress/atomic-blocks/pull/230.
