### ISSUE TITLE
Container max width causes error

### ISSUE THREAD

**Issue by mikemcalister** [studiopress/atomic-blocks#231]
**Describe the bug**
The container block will produce an error if the default max width is cleared after setting it. This is likely due to outputting the width without checking for it first. 

**Expected behavior**
You should be able to clear out the max width and save/reload with no issues.

**Comment by jayhill90** [comment]
I want to say that by not having a default value set, we could avoid this issue.

**Comment by jayhill90** [comment]
Seems community members site's are being affected. https://genesiswp.slack.com/archives/C04525Y9S/p1575556829130500

**Comment by mindctrl** [comment]
Related request: https://wordpress.org/support/topic/feature-request-739/
