### ISSUE TITLE
I can't add negative margin values for AB container block

### ISSUE THREAD

**Issue by inakicalvo** [studiopress/atomic-blocks#244]
**Describe the bug**
I can't add negative margin values for AB container block. There is a minimum value of 0 set, so I can enter a negative value.

Negative values are useful for moving objects around in the layout and some StudioPress themes use them (e. g., Revolution Pro's homepage).

**To Reproduce**
1. Add an AB Container block
2. Set a negative margin value
3. Save changes
4. The negative value is gone!

**Expected behavior**
I'd like to be able to add negative values.

**Screenshots**
![Captura de pantalla 2019-09-30 a las 21 58 28](https://user-images.githubusercontent.com/6794878/65911843-86bf5e00-e3cd-11e9-9051-9f3c6a1cc23b.png)

**Version**
- 2.1.0

**Comment by mikemcalister** [comment]
Hi there, doing a bit of cleanup in the issues here. Negative margins is something we're interested in, but not until we can do mobile styles. Core is working on adding mobile styles, and at that point, we can implement this. I'm going to close the issue since this is in our backlog.
