### ISSUE TITLE
Improve HR styles in TwentyTwenty

### ISSUE THREAD

**Issue by mikemcalister** [studiopress/atomic-blocks#262]
**Describe the bug**
TwentyTwenty makes some pretty odd style decisions for some elements like HRs, [as seen here](https://share.getcloudapp.com/12uEQDLJ). We'll need a way to provide fixes for these without changing the default AB block styles. 

**To Reproduce**
1. Activate AB and the 2020 theme
2. Add an HR to the page and view it on the front end
3. Cry because this is a bad design decision

**Expected behavior**
The HR style should reflect what the user has chosen in the editor. 

**Screenshots**
![hr image](https://p199.p4.n0.cdn.getcloudapp.com/items/12uEQDLJ/Image+2019-11-07+at+10.55.32+AM.png?v=91563ba0e52a0c7c37fa94d3fc0aa55c)

**Comment by mindctrl** [comment]
Fixed in https://github.com/studiopress/atomic-blocks/pull/271
