### ISSUE TITLE
AMP applies  object-fit: contain; to container block background image

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/atomic-blocks#279]
**Describe the bug**

With the WP AMP plugin active, the following CSS is applied to the image used for the block background:

```css
amp-img.amp-wp-enforced-sizes[layout="intrinsic"] > img {
    object-fit: contain;
}
```

Markup applied is:
```html
<img decoding="async" alt="" src="https://example.com/wp-content/uploads/2019/12/image.jpg" class="i-amphtml-fill-content i-amphtml-replaced-content">
```

The result is that the image no longer covers the background of the container.

<img width="932" alt="Screen Shot 2019-12-11 at 1 27 33 PM" src="https://user-images.githubusercontent.com/1271053/70648912-15e0c180-1c1a-11ea-8068-486f10a1266f.png">

**To Reproduce**
1. Set up a site with https://wordpress.org/plugins/amp/
2. Insert a container block and choose a background image.
3. View the front-end 
4. Note the image doesn't cover the container

**Expected behavior**
Image will appear as it does on a non-AMP site.

**Screenshots**

**Tested Version**
- 2.3.0

**Comment by westonruter** [comment]
Proposed fix: #292
