### ISSUE TITLE
PHP 7.4 error notices when using the grid block without relevant thumbnails

### ISSUE THREAD

**Issue by nickcernis** [studiopress/atomic-blocks#289]
**Describe the bug**
Under PHP 7.4 there are a couple of notices above the editor if the grid block is in use and the user has not regenerated thumbnails to create the `ab-block-post-grid-landscape` and `ab-block-post-grid-square` sizes:

~~~
[19-Dec-2019 19:43:30 UTC] PHP Notice:  Trying to access array offset on value of type bool in /Users/nick/Documents/sites/dev/wp-content/plugins/atomic-blocks/src/blocks/block-post-grid/index.php on line 464
[19-Dec-2019 19:43:30 UTC] PHP Notice:  Trying to access array offset on value of type bool in /Users/nick/Documents/sites/dev/wp-content/plugins/atomic-blocks/src/blocks/block-post-grid/index.php on line 480
~~~

The issue is that `wp_get_attachment_image_src` can return an array or boolean, but AB assumes an array and tries to access it here:

https://github.com/studiopress/atomic-blocks/blob/1d6d8df5b8d36d67ceea352ffa0d099a9c65e693/src/blocks/block-post-grid/index.php#L464

https://github.com/studiopress/atomic-blocks/blob/1d6d8df5b8d36d67ceea352ffa0d099a9c65e693/src/blocks/block-post-grid/index.php#L480

If `$feat_img_array` is false due to missing thumbnails, then using the array accessor throws the above notices because PHP 7.4 no longer allows us to treat non-arrays like an array:

- https://core.trac.wordpress.org/ticket/47704
- https://wiki.php.net/rfc/notice-for-non-valid-array-container

This is a low-priority edge case that's hard to reproduce (I encountered it after running theme setup with Magazine Pro), but filing in case it comes up.

One fix would be to check for the array before accessing it for any returned values of type `array|mixed`:

```php
if ( is_array( $feat_img_array ) ) {
	return $feat_img_array[0];
}
```

**Version**
- develop
- 2.4.0

**Comment by henscu** [comment]
I'm finding the problem very easy to reproduce on my local development environment (MacOS)...

I encounter it after running theme setup for **Genesis Sample Theme**, and I'm finding it tricky to regenerate my local thumbnails on localhost...

My local development environment is:

- Flywheel Local 5.2.3 (MacOS)
- Atomic Blocks 2.4.0
- PHP 7.4.1
- WordPress 5.3.2
- MySQL 8.0.16
