### ISSUE TITLE
AB 2.5.0 and 2.5.1 don't work correct, esspecialy with polylang

### ISSUE THREAD

**Issue by JSoko** [studiopress/atomic-blocks#308]
Until V 2.4.0 Atomic Blocks works well

After Update to 2.5.0 or 2.5.1 the stylsheets are broken as long as polylang plugin is activated.

For further description please see
https://wordpress.org/support/topic/ab-colums-broken/
https://wordpress.org/support/topic/malfunction-together-with-atomic-blocks-2-5/

site: https://tm-academy.de

**Comment by JSoko** [comment]
https://wordpress.org/support/topic/atomic-blocks-overriding-font-awesome-5-pro-kit-in-css/

https://wordpress.org/support/topic/ab-post-and-page-grid-not-working-properly-after-update/

**Comment by JSoko** [comment]
Could it deal with this PR?
https://github.com/studiopress/atomic-blocks/pull/294

**Comment by mindctrl** [comment]
@JSoko it could be that, though I don't know why Polylang would break loading styles in such a way. We're looking into it and will issue a fix as soon as possible.

**Comment by mindctrl** [comment]
PR: https://github.com/studiopress/atomic-blocks/pull/310

**Comment by JSoko** [comment]
Yes, it works again. Thank you very much for the fast service!
