### ISSUE TITLE
IE11 grid layout: improving support 

### ISSUE THREAD

**Issue by tnog** [studiopress/atomic-blocks#315]
Hi,

I'm troubleshooting a recent project's grid AB based column layouts on IE11 and there still seems to be inadequate support? A simple fix would be to add additional `-ms` specific prefixed properties for `grid-template-columns` and `grid-template-rows`:

```
-ms-grid-columns
-ms-grid-rows
```

I imported the included src stylesheets in src > block-column-inner > styles > style.scss into my theme, and setup autoprefixer for grid support. Including an example of my postcss.config.js file below:

```
/* eslint-disable */

const cssnanoConfig = {
  preset: ['default', { discardComments: { removeAll: true } }]
};

module.exports = ({ file, options }) => {
  return {
    parser: options.enabled.optimize ? 'postcss-safe-parser' : undefined,
    plugins: {
      autoprefixer: {
        grid: true,
        browsers: ['>1%'],
      },
      cssnano: options.enabled.optimize ? cssnanoConfig : false,
    },
  };
};
```

This seems like a relatively simple way to add better support for IE11?

**Comment by mikemcalister** [comment]
Hey @tnog, what kind of issues are you seeing? You didn't mention what was actually wrong with the columns. Feel free to share a screenshot and we'll take a closer look.

**Comment by tnog** [comment]
Hi @mikemcalister  screenshots below
![bs_win10_IE_11 0 (1)](https://user-images.githubusercontent.com/2049299/74876630-de2c7f00-5318-11ea-9d38-1c902f024769.jpg)
![bs_win10_IE_11 0](https://user-images.githubusercontent.com/2049299/74876633-df5dac00-5318-11ea-89c9-67794611c1e0.jpg)

**Comment by tnog** [comment]
After including `-ms-grid-columns` and `-ms-grid-rows`

![bs_win10_IE_11 0 (2)](https://user-images.githubusercontent.com/2049299/74877018-978b5480-5319-11ea-9b83-fc2240027d63.jpg)

![bs_win10_IE_11 0 (3)](https://user-images.githubusercontent.com/2049299/74877007-935f3700-5319-11ea-98e9-5deafe1bb228.jpg)

**Comment by mikemcalister** [comment]
Thanks for sending the screenshots! Is your [live site](https://bridgeyardplaceholde-dev.sitedistrict.com/) with or without these fixes? We do have support for both `-ms-grid-columns` and `-ms-grid-rows`, as you can see in the [source here](https://github.com/studiopress/atomic-blocks/blob/develop/src/blocks/block-column-inner/styles/style.scss), so we must have missed a prefix. Do you know which prefixes were added that weren't there already?

**Comment by mikemcalister** [comment]
Also, it looks like you are on Atomic Blocks 2.4.0, and there were a number of IE Grid fixes in the newer versions. Please try updating the plugin to see if that helps.

**Comment by tnog** [comment]
@mikemcalister Thanks! Looks like updating the plugin to the newest version addressed the issue, and went ahead and removed the custom stylesheet that I added. I'll go ahead and close the issue since it's been resolved.
