### ISSUE TITLE
Issue on post grid 4 columns layout after new version update 

### ISSUE THREAD

**Issue by AnchoredDesign** [studiopress/atomic-blocks#319]
we are using post grid in our new theme as 4 columns and it just ruin layout having 4 columns till layout with 3 columns it works but for 4 columns it default to 2 columns..
I just found there is css update "/lib/atomic-blocks/dist/blocks.style.build.css" in new version that causing issue

`.ab-block-post-grid .is-grid.columns-4 .ab-is-grid.ab-columns-4{-ms-grid-columns:1fr 1fr 1fr 1fr;grid-template-columns:1fr 1fr 1fr 1fr}`

here need comma after .ab-block-post-grid .is-grid.columns-4

`.ab-block-post-grid .is-grid.columns-4, .ab-is-grid.ab-columns-4{-ms-grid-columns:1fr 1fr 1fr 1fr;grid-template-columns:1fr 1fr 1fr 1fr}`

Please update and release new version soon please.. it is affecting layout badly

**Comment by nickcernis** [comment]
Thanks for the report, @AnchoredDesign. This was fixed in https://github.com/studiopress/atomic-blocks/pull/314 and will likely make it into an upcoming release.

**Comment by mindctrl** [comment]
@AnchoredDesign Nick's correct, this fix will be in the next update. Sorry for the problem, and thanks for the report.

**Comment by AnchoredDesign** [comment]
Thank You ..waiting for new release..
