### ISSUE TITLE
Pricing table styles in Gutenberg plugin

### ISSUE THREAD

**Issue by mikemcalister** [studiopress/atomic-blocks#329]
**Describe the bug**
The Pricing Table block needs refinement when the Gutenberg plugin is active. The editor styles are being affected by the prefix change.

**To Reproduce**
1. Update the Gutenberg plugin to the latest version.
2. Add the Pricing Table block and notice how the spacing between the tables is not right. 
3. The gap setting also is not displaying properly.

**Expected behavior**
The pricing table should behave the same way with core and the Gutenberg plugin installed.

**Screenshots**

**Version**
- 2.6.0

**Comment by mindctrl** [comment]
Related #328
