### ISSUE TITLE
WP 5.4 heading class removed in editor

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/atomic-blocks#341]
**Describe the bug**
The wp-block-heading class used at https://github.com/studiopress/atomic-blocks/blob/develop/src/blocks/block-layout/styles/style.scss#L63 is not present in WP 5.4.

**To Reproduce**
1. Install WP 5.4 RC5 with a theme such as Authority Pro.
2. Create a new page and insert a Hero Header section.
3. Note the text color for the heading is not white in the editor.

**Expected behavior**
Text will be white.

**Screenshots**

<img width="1447" alt="Screen Shot 2020-03-30 at 9 07 38 AM" src="https://user-images.githubusercontent.com/1271053/77915943-523a3b00-7266-11ea-962e-aafebe0784ce.png">

**Comment by mindctrl** [comment]
Related: https://github.com/studiopress/atomic-blocks/issues/328

**Comment by mikemcalister** [comment]
The `ab-white-text` class was introduced before the headings had color options. Long term, it's probably better to remove this style and apply the color to the heading with the picker.

Short term, I'll try and patch the color fix so there isn't any immediate impact to SP themes or users who have sections or layouts with the class applied.

**Comment by jonschr** [comment]
It might also be good, as a default, to style headings, paragraphs, and lists to white in an overridable way when inside a container which has a background image. Perhaps a separate issue (sort of), but it would be amazing for containers to get a class of .has-background-XX-color added when there's a background color – and if it's possible to programmatically determine whether that background color is on the whole dark or light, you could add a class of .has-background-dark or .has-background-light then style the headings based on that, which would make for better defaults.
