### ISSUE TITLE
IconButton is deprecated

### ISSUE THREAD

**Issue by johnstonphilip** [studiopress/atomic-blocks#344]
I noticed that we are using `IconButton` component in a few places:

https://github.com/studiopress/atomic-blocks/search?q=IconButton&unscoped_q=IconButton

It is now [deprecated](https://make.wordpress.org/core/2020/02/13/an-updated-button-component-in-wordpress-5-4/) as of WP 5.4.

**Comment by mindctrl** [comment]
This is being fixed in https://github.com/studiopress/atomic-blocks/pull/373.
