### ISSUE TITLE
custom attributes addition

### ISSUE THREAD

**Issue by jayna06** [studiopress/atomic-blocks#352]
Hello, is that possible to add extra attributes to Atomic Blocks like we do with core blocks?
Ex: https://chap.website/adding-a-custom-attribute-to-gutenberg-block/ 
This is working for core blocks but when I put atomic block - block name its not working.. 
Anything if I can do, could be helpful...

**Comment by jayna06** [comment]
is this not issue ? I can add custom fields to core blocks but not atomic blocks...

**Comment by mindctrl** [comment]
We use this for development tracking only - not support. Please open a support thread on wordpress.org and include all the code you're trying that isn't working.
