### ISSUE TITLE
Breaks Custom Fields Display

### ISSUE THREAD

**Issue by wpsmith** [studiopress/atomic-blocks#369]
**Describe the bug**
The user cannot display Custom Fields in the Gutenberg editor.

**To Reproduce**
1. Install Atomic Blocks & Activate.
2. Click on to edit any post.
3. Click the top right menu (vertical dots)
4. Click on Options
5. Check Custom Fields
6. Click Enable & Reload

**Expected behavior**
Custom Fields area should appear, but the check field does not save appropriately.

**Screenshots**
<img width="388" alt="Screenshot 2020-05-13 23 11 57" src="https://user-images.githubusercontent.com/817366/81888428-4cc35680-956f-11ea-84f3-2307093bd1ac.png">

This should appear but doesn't.
<img width="885" alt="Screenshot 2020-05-13 23 12 52" src="https://user-images.githubusercontent.com/817366/81888432-4e8d1a00-956f-11ea-9406-d69b00fec1f2.png">

**Version**
- 2.8.2

**Device and browser information**
 - OS: MacOS
 - Browser: ALL - Chrome (81.0.4044.138); Firefox (77.0b3); Safari (13.0.4 - 15608.4.9.1.3)

**Additional context**

**Comment by nickcernis** [comment]
Thanks for the report, @wpsmith.

I haven't been able to reproduce this so far with AB 2.8.2 on macOS/Chrome. Atomic Blocks being active doesn't affect Custom Fields visibility or settings for me:

![ab-custom-fields](https://user-images.githubusercontent.com/647669/81907132-92137280-95c7-11ea-8a1a-49b68df66c18.gif)

1. For this:

> Custom Fields area should appear, but the check field does not save appropriately.

Do you mean that the check field appears unticked when you revisit the setting after ticking it and saving? 

If so, one thing that can cause this is any code that removes `custom-fields` post type support. For example, if I add this:

```php
add_action('admin_init', 'sp_remove_custom_fields_from_posts');
function sp_remove_custom_fields_from_posts() {
	remove_post_type_support( 'post', 'custom-fields' );
}
```

Then “Custom fields” becomes unchecked after I check it, save, and revisit that panel for posts, even with Atomic Blocks deactivated.

Atomic Blocks does not call `remove_post_type_support` anywhere I could find (or use the `custom-fields` key anywhere), so it's something you could check other active plugins or custom code for.

If instead you mean that the state is saved correctly but the active state appears to have no effect, you could check that the admin page loads completely. (No missing closing `</html>` tag in the source, or fatal PHP errors that would cut output short.) There might be an error elsewhere preventing the meta box from loading.

It would also useful to know:

1.  Can you save the Custom Fields setting on the same post as soon as you disable Atomic Blocks, without making other changes? (It's implied in your report, but helpful to confirm.)

2. Are Custom Fields missing or impossible to activate from all posts/pages with Atomic Blocks active, or just for a specific post type?

**Comment by wpsmith** [comment]
Stink. I thought I disabled everything. The problem was an old version of Yoast where there was a JS error on the page. Note, there is a core issue with [Gutenberg](https://github.com/WordPress/gutenberg/issues/16333) and post types that do not support Custom Fields.

**Comment by nickcernis** [comment]
@wpsmith Glad you tracked it down! Thanks for the update and for digging up that issue. Makes sense that the option should be hidden on post types that don't support custom fields.
