### ISSUE TITLE
Overly opinionated AB Container block

### ISSUE THREAD

**Issue by lizkaraffa** [studiopress/atomic-blocks#38]
Can there be a way to turn off the automatically populated inline-styling (i.e. all the padding, margin, max-width, and background color). It feels like those should only result in inline-styling if the user sets them versus automatically being set by default. This really conflicts with any theme styling and forces the use of `!important` because no level of specificity will trump inline styling.

**Comment by mikemcalister** [comment]
Thanks for the feedback, Liz. We'll take a look at this in the releases after WordPress 5.0 is released!
