### ISSUE TITLE
Category selection in Post Grid block it's not saving

### ISSUE THREAD

**Issue by faia20** [studiopress/atomic-blocks#396]
**Category select bug:**
When selecting the category for a Post Grid block, nothing changes.

**To Reproduce**
1. Create a Post Grid block
2. Select a Category (nothing changes visually)
3. Click on other block and then go back to previous Post Grid block
4. The category selection is back to "All"

**If you change the category and then save the post, you get the same issue: The post grid will be back to all.**

**Versions**
- Atomic Blocks: Version 2.8.5
- Wordpress: Version 5.5
- Gutenberg: Version 2.8.5
- Genesis Framework: Version: 3.3.3

**Device and browser information**
 - OS: Windows 10
 - Browser: Chrome
 - Chrome Version 84.0.4147.135

**Comment by nickcernis** [comment]
Thank you for the report, @faia20.

This relates to an issue with WordPress core that should be fixed in an upcoming WordPress update: 

https://github.com/WordPress/gutenberg/pull/24516

**Comment by faia20** [comment]
> Thank you for the report, @faia20.
> 
> This relates to an issue with WordPress core that should be fixed in an upcoming WordPress update:
> 
> [WordPress/gutenberg#24516](https://github.com/WordPress/gutenberg/pull/24516)

Thanks Nick! I hope that fix is released pretty soon.

**Comment by faia20** [comment]
This issue wasn't fixed with new wordpress update 5.5.1 and atomic blocks Version 2.8.5

**Comment by nickcernis** [comment]
@faia20 The category setting saves correctly for me and another team member in 5.5.1.

Please could you try refreshing your browser cache and double-checking the site is running 5.5.1?

**Comment by mindctrl** [comment]
Per the comments here, disabling the Gutenberg plugin will fix it for you: https://github.com/WordPress/gutenberg/pull/24516#issuecomment-685632074

**Comment by faia20** [comment]
> Per the comments here, disabling the Gutenberg plugin will fix it for you: [WordPress/gutenberg#24516 (comment)](https://github.com/WordPress/gutenberg/pull/24516#issuecomment-685632074)

it worked! Thanks!!
