### ISSUE TITLE
WP 5.5: changing column count does not adjust columns

### ISSUE THREAD

**Issue by nickcernis** [studiopress/atomic-blocks#397]
Discovered and fixed in Genesis Blocks. Those fixes could be ported here:

https://github.com/studiopress/genesis-blocks/pull/54
https://github.com/studiopress/genesis-blocks/pull/55
https://github.com/studiopress/genesis-blocks/issues/47

https://wordpress.org/support/topic/change-the-number-of-columns-that-cant-be-dynamically-changed-anymore/

**Comment by mindctrl** [comment]
This was closed via https://github.com/studiopress/atomic-blocks/pull/402.
