### ISSUE TITLE
Styles repeated multiple times in compiled stylesheets

### ISSUE THREAD

**Issue by tyrann0us** [studiopress/atomic-blocks#58]
Hi,
there's a bug in how to compile the stylesheets.

See

https://github.com/ArrayHQ/atomic-blocks/blob/f5ae35323bc86c1e44ee1c3542d81fdd42bb96d2/dist/blocks.style.build.css#L1-L12

and

https://github.com/ArrayHQ/atomic-blocks/blob/f5ae35323bc86c1e44ee1c3542d81fdd42bb96d2/dist/blocks.editor.build.css#L1-L12

As you can see, many CSS rules are repeated 12 times. This is because https://github.com/ArrayHQ/atomic-blocks/blob/master/src/common.scss is prepended to every block's stylesheet.

**Comment by mindctrl** [comment]
Related: https://github.com/webpack-contrib/sass-loader/issues/145
