### ISSUE TITLE
Network activating the plugin doesn't redirect to correct URL

### ISSUE THREAD

**Issue by remkus** [studiopress/atomic-blocks#82]
When you network activate the plugin in a WordPress multi-site installation, the redirect after activation expects to be at the site level, not network level. 

Meaning, the actual URL of the Atomic dashboard page is `/wp-admin/admin.php?page=atomic-blocks`, but I've been redirect to `/wp-admin/network/admin.php?page=atomic-blocks`. Which in turns results in a "you don't have permission notice".

**Comment by mindctrl** [comment]
Thanks for the report! We'll get this fixed up soon.
