### ISSUE TITLE
Post Grid excerpt length option doesn't work

### ISSUE THREAD

**Issue by mindctrl** [studiopress/atomic-blocks#83]
It's hardcoded to 55 here: https://github.com/ArrayHQ/atomic-blocks/blob/1868ee1848e84a91772a21d9f6dd10b85e717e61/src/blocks/block-post-grid/index.php#L182

Should be `$attributes['excerptLength']` instead.

Reported https://wordpress.org/support/topic/cannot-change-excerpt-length-in-post-page-grid-block/#post-11357524

**Comment by sarahannnicholson** [comment]
AB plugins version: `Version 1.7.1`

Hmm it looks like I'm not getting truncated excerpts. Could someone double check ?

Here's what I am seeing: 

On one of my posts, I have the following excerpt: 
"This is an excerpt that is very long to see if we can truncate it at some point after a really long sentence. This is an excerpt that is very long to see if we can truncate it at some point after a really long sentence. This is an excerpt that is very long to see if we can truncate it at some point after a really long sentence"

On a page, I am using the AB posts and page grid. 

In the inspector controls I set the excerpt to 40 (word??). 
This trims my excerpt to the following: 
"This is an excerpt that is very long to see if we can truncate it at some point after a really long sentence. This is an excerpt that is very long to see if we can truncate it at some" 

Which is great! but when I preview my page, I get the full excerpt:
"This is an excerpt that is very long to see if we can truncate it at some point after a really long sentence. This is an excerpt that is very long to see if we can truncate it at some point after a really long sentence. This is an excerpt that is very long to see if we can truncate it at some point after a really long sentence"
